services:
  - type: web
    name: tailleur-kidira
    runtime: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
